global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Demo target (puedes añadir más servicios aquí)
  - job_name: 'demo-service'
    static_configs:
      - targets: ['demo-service:8080']
